config/routes.rb
Rails.application.routes.draw do

  root "access#landingpage", as: :landing_page
  
  post '/access/login', to: "access#attempt_login", as: 'login'

  get 'access/landingpage'

  get 'access/about'

  delete '/logout', to: "access#logout", as: "logout"

  get 'searches/index', as: "search"
  
  post 'searches/results', to: "searches#resultsShow"

  resources :users

  patch "/users/:id/gift" => 'gifts#update', as: :gift

end

# From rake routes
#        Prefix Verb URI Pattern                                  Controller#Action
#        landingpage GET    /                                     access#landingpage
# access_landingpage GET    /access/landingpage(.:format)         access#landingpage
#     searches_index GET    /searches/index(.:format)             searches#index
#   searches_results POST   /searches/results(.:format)           searches#results
#                    GET    /searches/results/:category(.:format) searches#resultsShow
#              users GET    /users(.:format)                      users#index
#                    POST   /users(.:format)                      users#create
#           new_user GET    /users/new(.:format)                  users#new
#          edit_user GET    /users/:id/edit(.:format)             users#edit
#               user GET    /users/:id(.:format)                  users#show
#                    PATCH  /users/:id(.:format)                  users#update
#                    PUT    /users/:id(.:format)                  users#update
#                    DELETE /users/:id(.:format)                  users#destroy
#               gift PATCH  /users/:id/edit(.:format)             gifts#update

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # Search page
  def index
  end

  # Showing seach results
  def resultsShow
    category = category_converter params[:category].downcase
    radius   = params[:radius]
    @users = search_function(category, radius)
  end

  
  private
  def search_function(category, radius)
    gift_results = Gift.where(category_id: category)

    # Removing any gifts related to the logged in user
    if session[:user_id]
      filtered_results = gift_results.reject { |result| result.user_id == session[:user_id] }
    else
      filtered_results = gift_results
    end

    users = filtered_results.map { |gift| gift.user}

    if session[:user_id]
      # Creating a variable that can use the perimeter_search call, defined in Zipcode class (zipcode.rb)
      current_user = User.find_by_id(session[:user_id])
      zip = Zipcode.find_by_zipcode(current_user.zipcode)

    else
      zip = Zipcode.find_by_zipcode("66952") # 66952 is the geographic center of the USA. It is Lebanon, KS
    end # :user_id conditional

    # Getting all zipcodes within a given radius
    valid_locations = zip.perimeter_search(radius)

    location_zips = valid_locations.map { |item| item[:zipcode] }

    # Selecting only users that are within the valid_lacations
    distant_users = users.select do |user| 
            location_zips.include?(user.zipcode)  
    end # users.select

    return distant_users.uniq
  end # search_function

  # Helper function for converting user friendly paramaters to data friendly stored integer representation
  def category_converter param
    if param == "time"
      return 1
    elsif param == "service"
      return 2
    elsif param == "money"
      return 3
    elsif param == "object"
      return 4
    end
  end

  def search_params
    params.require(:search).permit(:category, :radius, :zipcode )
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<!-- nav bar partial -->
<div class="container text-center page-background-color page-sizing">
<h1>Search Profiles</h1>

<%= form_tag("/searches/results", method: "post", class: "form-inline") do %>

  <% unless session[:user_id] %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <p>What is your ZIP code?&nbsp;
        <%= text_field_tag(:zipcode, nil, placeholder: "Your Zip Code")%>
        </p>
      </div>
    </div>
  <% end %>

  <!-- <div class="row"> -->
  <div class="text-center">
    <!-- <div class="col-md-6"> -->
    <p>
      What category of items are you interested in?&nbsp;
      <%= select_tag(:category, options_for_select([
          ['Time', "Time"],
          ['Service', "Service"],
          ['Donation', "Money"],
          ['Object', "Object"]
         ], "Time")) %>
        </p>
    <!-- </div> -->
    <!-- <div class="col-md-6"> -->
    <p>
      How far away can it be?&nbsp;
      <%= select_tag(:radius, options_for_select([
          ['Distance is not applicable', 5000], 
          ['Up to 1 mile', 1], 
          ['Up to 2 miles', 2], 
          ['Up to 3 miles', 3], 
          ['Up to 4 miles', 4], 
          ['Up to 5 miles', 5], 
          ['Up to 6 miles', 6], 
          ['Up to 7 miles', 7], 
          ['Up to 8 miles', 8], 
          ['Up to 9 miles', 9], 
          ['Up to 10 miles', 10], 
          ['Up to 15 miles', 15], 
          ['Up to 20 miles', 20], 
          ['Up to 30 miles', 30], 
          ['Up to 50 miles', 50]
          ], 7000)) %>
          </p>
    <!-- </div> -->
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3 submit-button">
      <%= submit_tag("Search")%>
    </div>
   
  </div>

<% end %>
<div id="loading">
  <span>LOADING</span>
</div>

</div>
</div>
</div>

app/views/searches/resultsShow.html.erb
<!-- coming from resultsShow.html.erb -->
<div class="container page-background-color">
  <div class="row search-results-header">
    <div class="col-md-2">
      <a href="/searches/index">
        <p class="text-center">Back to Search</p>
      </a>
    </div>
    <div class="col-md-8 text-center">
      <h1>Search Results</h1>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>
<div class="flex-container container page-background-color">

  <% @users.each do |user| %>
    <% if session[:user_id] %>
      <a href="/users/<%= user.id %>">
    <% else %>
      <% flash[:notice] = "Please log in or sign up!" %>
      <a href="<%= landingpage_path %>" >
    <% end %>

    <div class="flex-items-default text-center">
      <div class="profilePagePhoto center" style="background-image: url(<%= user.profile_pic %>); background-size: cover; background-position:center;"></div>
      <h1>
        <%= user.first_name %>
      </h1>

      <div>
        <h3>
          Give 
          <small> 
            <% if user.gifts.find_by_type_id(1).category_id == 1 %>
            Time
            <% elsif user.gifts.find_by_type_id(1).category_id == 2 %>
            Service
            <% elsif user.gifts.find_by_type_id(1).category_id == 3 %>
            Donation
            <% elsif user.gifts.find_by_type_id(1).category_id == 4 %>
            Object
            <% end %>
          </small>
        </h3>
        <p>
          <%= user.gifts.find_by_type_id(1).title %>
        </p>
        <h3>
          Get
          <small> 
            <% if user.gifts.find_by_type_id(2).category_id == 1 %>
            Time
            <% elsif user.gifts.find_by_type_id(2).category_id == 2 %>
            Service
            <% elsif user.gifts.find_by_type_id(2).category_id == 3 %>
            Donation
            <% elsif user.gifts.find_by_type_id(2).category_id == 4 %>
            Object
            <% end %>
          </small>
        </h3>
        <p>
          <%= user.gifts.find_by_type_id(2).title %>
        </p>
      </div>
    </div>
    <% if session[:user_id] %>
      </a>
    <% end %>
  <% end %>
</div>