config/routes.rb
Rails.application.routes.draw do

  root "access#landingpage", as: :landing_page
  
  post '/access/login', to: "access#attempt_login", as: 'login'

  get 'access/landingpage'

  get 'access/about'

  delete '/logout', to: "access#logout", as: "logout"

  get 'searches/index', as: "search"
  
  post 'searches/results', to: "searches#resultsShow"

  resources :users

  patch "/users/:id/gift" => 'gifts#update', as: :gift

end

# From rake routes
#        Prefix Verb URI Pattern                                  Controller#Action
#        landingpage GET    /                                     access#landingpage
# access_landingpage GET    /access/landingpage(.:format)         access#landingpage
#     searches_index GET    /searches/index(.:format)             searches#index
#   searches_results POST   /searches/results(.:format)           searches#results
#                    GET    /searches/results/:category(.:format) searches#resultsShow
#              users GET    /users(.:format)                      users#index
#                    POST   /users(.:format)                      users#create
#           new_user GET    /users/new(.:format)                  users#new
#          edit_user GET    /users/:id/edit(.:format)             users#edit
#               user GET    /users/:id(.:format)                  users#show
#                    PATCH  /users/:id(.:format)                  users#update
#                    PUT    /users/:id(.:format)                  users#update
#                    DELETE /users/:id(.:format)                  users#destroy
#               gift PATCH  /users/:id/edit(.:format)             gifts#update

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Good&amp;Co.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
  <!-- Widget config for Upload Care -->
  <script>
    UPLOADCARE_PUBLIC_KEY = '8f615b911b6092cc8a13';
    UPLOADCARE_TABS = 'all';
    UPLOADCARE_IMAGES_ONLY = true;
    UPLOADCARE_PREVIEW_STEP = true;
    UPLOADCARE_CLEARABLE = true;
  </script>
  <script charset="utf-8" src="https://ucarecdn.com/widget/2.0.2/uploadcare/uploadcare.full.min.js"></script>
  <!-- end -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js">
  </script>
</head>
<body>
  
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid" class="navcontainer">
      <a href="/">
      <p class="navbar-text navbar-left"><span>Good</span>&amp;Co.</p>
      </a>
      <ul class="nav navbar-nav navbar-right">
        <% if !session[:user_id] %>
          <li>
            <%= form_tag(login_path, class: 'navbar-form navbar-left extra-padding-to-nav') do %>
              <%= label_tag(:email) %>
              <%= text_field_tag(:email, params[:email]) %>

              <%= label_tag(:password) %>
              <%= password_field_tag(:password, params[:password]) %>

              <%= submit_tag("Login") %>
            <% end %>
          </li>
        <% end %>
        <li><%= link_to("Search", controller: "searches", action: "index") %></li>
        <li><%= link_to("About", controller: "access", action: "about") %></li>
        <% if session[:user_id] %>
          <li><%= link_to("Profile", "/users/#{session[:user_id]}") %></li>

          <li>
            <% if session[:user_id] %>
              <%= link_to "Edit Profile", "/users/#{session[:user_id]}/edit"%>
            <% end %> 
          </li>
          <li><%= link_to("Logout", logout_path, method: :delete) %></li>
        <% else %>
          <li><%= link_to("Sign Up", "/users/new") %></li>
        <% end %>
      </ul>
      
    </div>
  </nav>

  <% flash.each do |key, value| %>
  
    <% if key == "notice" %>
      <%= content_tag :div, value, class: "text-center alert alert-warning flashMessage" %>
    <% elsif key == "alert" %>
      <%= content_tag :div, value, class: "text-center alert alert-danger flashMessage" %>
    <% else %>
      <%= content_tag :div, value, class: "text-center alert alert-success flashMessage" %>
    <% end %>
  <% end %>

<%= yield %>
<script>
$( ".submit-button > input" ).click(function() {
  // alert( "Handler for .click() called." );
  $('#loading').css('visibility', 'visible')
});
</script>
</body>
</html>